Wait for capture options to be opened in E2E tests
google/orbit pull request #4145
Opened 2022-08-29 13:03 UTC by karupayun

In this PR we are adding a wait_for_conditions to wait until the capture
option is open both when setting the auto-frame-track capture options
and when setting memory sampling period. 

This should fix the flakiness in instrument_function E2E tests. Since the 
test took 20 seconds to open the dialog, I'm setting 40 sec for timeout.
I think it should be enough.

Bug: http://b/244148913

2022-08-30 08:03 UTC, antonrohr requested changes
There are 2 (or at least 1) more calls to `_show_capture_options_dialog()` in line 424 and 705. I think the call in 424 should definitely be guarded by the wait, I am unsure about 424. 

Why don't you do the wait inside of the function `_show_capture_options_dialog()`? I am not super familiar with these pywinauto scripts, but maybe you can even return the `capture_options_dialog`

2022-08-30 08:45 UTC, danielfenner approved these changes
Nit: 

Since I added a handful of similar changes in the past: How about adding something like
`wait_and_find_control` that wraps the `wait_for_condition` and the `find_control`?

2022-08-30 10:50 UTC, karupayun commented
> Nit:
> 
> Since I added a handful of similar changes in the past: How about adding something like `wait_and_find_control` that wraps the `wait_for_condition` and the `find_control`?

It makes a lot of sense for me. I created this bug and will probably tackle next week after branch cut.

2022-08-30 10:51 UTC, karupayun commented
> There are 2 (or at least 1) more calls to `_show_capture_options_dialog()` in line 424 and 705. I think the call in 424 should definitely be guarded by the wait, I am unsure about 424.
> 
> Why don't you do the wait inside of the function `_show_capture_options_dialog()`? I am not super familiar with these pywinauto scripts, but maybe you can even return the `capture_options_dialog`

Makes sense, I will modify this method to return capture_options_dialog

2022-08-30 11:02 UTC, karupayun commented
I made your changes, but I will wait until running the E2E tests in the signed build (~3 hours)

2022-08-31 08:11 UTC, karupayun commented
Test were all green.

2022-08-31 08:11 UTC, merged